@extends('app')

@section('title')
    @lang('general/title.terms')
    @parent
@stop

@section('content')
    <h1>@lang('general/title.terms')</h1>
    <hr/>
    <p>La plataforma INTERACPEDIA, entendiendo por tal el portal web y la aplicación móvil –app., es propiedad de la compañía IDEA MINDS GROUP S.A.S. (en adelante, todos ellos denominados INTERACPEDIA). Ésta tiene por objeto utilizar una metodología colaborativa de innovación abierta  que involucra conceptos sociales, tendencias mundiales y un nuevo formato dinámico de publicación de contenido, y la generación, administración y masificación de conocimiento práctico integrando los diferentes actores de la sociedad, tales como, pero no limitado, al gobierno, la industria, las universidades y estudiantes, utilizando para ello a las universidades u otros posibles actores que cuentan con tales herramientas, como laboratorios de interacción creativa, con el fin de darle un uso real a los proyectos de los estudiantes de las universidades del mundo (en adelante, todos ellos denominados los servicios).</p>
    <p>Los términos y condiciones generales de uso y las políticas de privacidad contenidas en este clausulado aplican tanto para el sitio web INTERACPEDIA (http://www.interacpedia.com) como para la aplicación móvil que lleva el mismo nombre. Están dirigidos a sus USUARIOS, entendiendo por tales a cualquier persona que ingrese al sitio web o haga uso de la aplicación INTERACPEDIA, con independencia del rol o la calidad de actor que ostente. Para dichos efectos, se advierte que en los términos de la legislación aplicable, los productos y servicios ofrecidos por INTERACPEDIA únicamente podrán ser utilizados o aprovechados por personas mayores de edad, no obstante poder ser usuarios finales niños, niñas o adolescentes menores de edad, siempre y cuando actúen a través de sus padres o representantes legales autorizados.</p>
    <p>Lea atentamente las siguientes cláusulas antes de hacer uso de la plataforma INTERACPEDIA ya que su utilización está sujeta a los términos y condiciones generales de uso y a las políticas de privacidad que más adelante se exponen, entendiendo que tales son los términos de un contrato legal entre los USUARIOS e INTERACPEDIA. Al acceder, navegar, descargar o usar cualquiera de las plataformas INTERACPEDDIA, usted reconoce que ha leído este clausulado, que lo ha entendido y se obliga, en consecuencia, a cumplir con los siguientes términos y condiciones como requisito indispensable para gozar de los servicios ofrecidos a través de INTERACPEDIA. La ausencia de aceptación de estos términos y condiciones, dará lugar a que Usted no pueda acceder a los servicios que prestamos.</p>
    <p class="title1">i. USUARIO Y CUENTA:</p>
    <p>Para acceder a los servicios de INTERACPEDIA, y de acuerdo con estos términos y condiciones en los que se detallan las normas generales de uso, Usted deberá crear una cuenta de USUARIO. Dicho registro se realizará de forma gratuita, no obstante reservarse INTERACPEDIA la posibilidad de generar cobros futuros para una o varias de las participaciones que esta plataforma ofrece. La creación de la cuenta de usuario requiere, como mínimo, información de usuario, correo electrónico y contraseña.  Asimismo, junto con su USUARIO será preciso construir un perfil de usuario con algunas de sus características básicas, entendiendo que tales son esenciales para la red INTERACPEDIA. Para ello, y con el fin de identificar necesidades, contexto y proyecciones, se le harán una serie de preguntas que tienen el propósito de dar respuesta  a los siguiente interrogantes: (i) ¿dónde está?, (ii) ¿hacia dónde quiere ir?, (iii) ¿cómo espera llegar?, y (iv) ¿qué necesita para lograrlo?.</p>
    <p>De acuerdo con su perfil y el sector al que pertenezca, se creará un USUARIO con alguna o varias de las siguientes características, no obstante la posibilidad de crear actores con tantas características como sea posible como miembro de la sociedad: (i) Actor-Universidad; (ii) Actor-Estudiante; (iii) 	Actor-Empresa; (iv)  Actor-Entidad Gubernamental; (v)	Actor-Publico en General; (vi) Actor – Profesor; (vii)        Actor - Mentor</p>
    <p>Serán USUARIOS solo las personas naturales, con independencia de la calidad que ostenten y no obstante la posibilidad de crear, a través de un mismo USUARIO, uno o varios de los perfiles anteriormente indicados, esto es, la posibilidad de que un mismo USUARIO represente uno o varios actores. Por favor tenga en cuenta que la información de USUARIO y perfil de usuario es personal e intransferible, motivo por el cual Usted debe abstenerse de compartirla con terceras personas. Le recordamos que Usted es el único responsable de conservar la confidencialidad y seguridad de la información de su cuenta, así como de las actividades que a través de ella se desarrollen. Por esto, INTERACPEDIA parte del supuesto de que toda la información que Usted suministra es entregada de buena fe, siendo ésta completa y veraz.</p>
    <p>A efectos de hacer uso de INTERACPEDIA, Usted se compromete a proporcionar y actualizar la información mínima requerida para acceder a los servicios y habilita a INTERACPEDIA para que almacene, use y dé tratamiento a sus datos de registro para conservar activa su cuenta, de acuerdo con los términos contenidos en las políticas de protección de datos personales que se incluyen a estos términos generales de uso. No obstante, en caso aquel en que el USUARIO decida inhabilitar su cuenta, INTERACPEDIA guardará su información por treinta (30) días adicionales después de haber hecho la solicitud; pasado dicho término tanto la información del usuario, como aquella que no se hubiere compartido públicamente por él será eliminada, no siendo posible su recuperación.</p>
    <p>Para la creación del USUARIO, se le enviará al correo electrónico ingresado por Usted al momento de apertura de su cuenta un correo de confirmación con el propósito de corroborar la veracidad de los datos compartidos y habilitar tanto el uso de la plataforma web como la descarga de la aplicación en cualquiera de sus dispositivos móviles. Otros mecanismos de confirmación también podrán ser utilizados por INTERACPEDIA, como es el envío de un código de verificación, entre otros, para habilitar la cuenta.</p>
    <p>A su vez, el usuario podrá acceder tanto a la plataforma web como a la aplicación móvil ingresando el usuario y la contraseña de su cuenta de usuario en twitter, Facebook, linkedin o google +, cuando tuviere alguna de las anteriores</p>
    <p class="title1">ii. NORMAS GENERALES DE USO Y OBLIGACIONES DEL USUARIO:</p>
    <p>Usted reconoce y acepta utilizar los servicios ofrecidos por INTERACPEDIA de acuerdo con estos términos y condiciones generales de uso, exclusivamente para los fines indicados en este escrito, en consideración a la Ley aplicable, la moral y las buenas costumbres, y absteniéndose de realizar cualquier uso comercial no autorizado. Reconoce, además, que la información compartida a través de INTERACPEDIA no acarrea responsabilidad alguna para INTERACPEDIA y es el USUARIO, al momento de postular soluciones a retos en particular, quien debe certificar que no conoce ninguna información igual que sea pública o disponible, ni que al compartirla lo hace en contravención a una norma o convención legal. Constituyen las principales obligaciones para el usuario:</p>
    <ol type="a">
        <li>Garantizar que la información suministrada para la creación de usuario y perfil es veraz y que Usted es titular de la misma.</li>
        <li>Garantizar ser el creador y/o titular de los contenidos intelectuales que sean compartidos a través de INTERACPEDIA, fueren retos o soluciones, o contar, de no ser creador o titular de dichos contenidos, con la correspondiente autorización para compartirlos con terceros.</li>
        <li>Abstenerse de compartir ideas, soluciones u otros que pertenezcan a terceras personas sin expresamente señalarlo y sin contar con el consentimiento de sus reales titulares. </li>
        <li>Adherirse a estas normales generales de uso y a cualquier otra regulación especial que resulte aplicable a los diferentes retos y/o soluciones que puedan compartirse a través de INTERACPEDIA por parte de otros participantes o actores.</li>
        <li>De acuerdo con su participación, como proponente de retos o soluciones, mero espectador, u otro, comprometerse a ceder los derechos de propiedad intelectual que resulten aplicables, y a guardar reserva y/o confidencialidad de la información que sea compartida a través de INTERACPEDIA, si a ello hubiere lugar.</li>
        <li>Aceptar que tanto los retos, como las soluciones y los participantes que se inscriban en INTERACPEDIA podrán ser rechazados y/o eliminados, de forma unilateral por INTERACPEDIA como interlocutor y/o por quienes hayan decidido crear el reto o postular las solución. No obstante, se advierte al USUARIO que, salvo que algo diferente se hubiere estipulado para el caso puntual, aquella información que se hubiere hecho pública pasará a ser de la comunidad en general y que una vez compartida la solución, incluso tratándose de un entorno cerrado y confidencial, no habrá lugar al retracto en dicha participación y ésta se someterá a las reglas generales de uso o a la reglas puntuales aplicables a un reto en particular.</li>
        <li>Cumplir con lo estipulado en las demás cláusulas previstas en los presentes términos y condiciones y abstenerse de realizar los siguientes usos indebidos:
            <ol type="a">
                <li>Suministrar datos falsos o incorrectos que puedan inducir a error a INTERACPEDIA o a terceros vinculados. En caso de que ello ocurra, INTERACPEDIA se reserva del derecho de rechazar, bloquear o suprimir la información que se suministre en contravención a lo indicado en este literal;</li>
                <li>Vulnerar, total o parcialmente, cualquier contenido de propiedad intelectual que haga parte de INTERACPEDIA o de sus actores y participantes de la red, tales como, pero no limitado a derechos de autor, marcas, patentes de invención, diseños industriales, secretos comerciales e industriales, o información confidencial;</li>
                <li>Realizar actos que puedan intencionalmente interferir con los servicios ofrecidos por INTERACPEDIA, tales como pero no limitados a la transmisión de virus, software malintencionado o cualquier otro código de naturaleza destructiva o perjudicial.</li>
                <li>Realizar cualquier uso comercial no autorizado de la plataforma y/o los contenidos compartidos a través de ella.</li>
            </ol>
        </li>
    </ol>
    <p class="title1">iii. PROPIEDAD INTELECTUAL:</p>
    <p>INTERACPEDIA es titular o persona autorizada respecto de los derechos de propiedad intelectual e industrial sobre la plataforma INTERACPEDIA, así como de contenidos o derechos de propiedad industrial e intelectual que en ellos se incorporen, incluyendo la plataforma tecnológica, signos distintivos (marcas u otros), diseños, patentes, códigos, métodos de trabajo, sistemas de información, know-how, dibujos, textos, bases de datos, videos y demás contenidos complementarios al desarrollo denominado INTERACPEDIA. La distribución, copia o utilización de cualquiera de estos contenidos, por fuera de lo indicado en estos términos y condiciones, cualquiera que fuera su finalidad, están prohibidas por la ley.</p>
    <p>La puesta a disposición del USUARIO de la plataforma denominada INTERACPEDIA y su descarga como aplicación móvil para dispositivos móviles, no implica, en ningún supuesto, la cesión de su titularidad ni la concesión de un derecho de uso exclusivo a favor del USUARIO. No obstante, INTERACPEDIA garantiza y garantizará en todo momento ser el creador intelectual, titular o persona autorizada para compartir los derechos y contenidos intelectuales que pone a disposición del USUARIO para la utilización de sus servicios. Del mismo modo, el USUARIO reconoce y acepta que aun en aquellos supuestos en los que éste hubiere intervenido para la consecución de mejoras en el desarrollo INTERACPEDIA, todos los derechos de propiedad intelectual, con excepción de aquellos que resulten del marco de cada Reto postulado y sus soluciones, serán de INTERACPEDIA.</p>
    <p>El USUARIO que ingrese en la plataforma INTERACPEDIA retos y/o soluciones, garantizará en todo momento ser el titular de los contenidos intelectuales que comparta. Si bien cada proyecto en el que participe el USUARIO puede estipular unas reglas de propiedad intelectual independientes a las que a continuación se señalan, en aquellos casos en que nada diferente se hubiere expresado, el USUARIO reconoce y acepta que:</p>
    <ol type="a">
        <li>Los retos postulados por los actores estudiantes y/o actores universidades, y en los que intervenga el USUARIO para ofrecer una solución, serán de su propiedad, como persona que ha creado la solución, salvo que algo diferente se especifique en la postulación del reto;</li>
        <li>Los Retos postulados por el USUARIO, cuando éste no fuera actor universidad y/o actor estudiantes, que sean resueltos por los actores estudiantes, docentes y/o universidades, serán del USUARIO que los haya postulado como Retos, salvo que algo diferente se hubiere especificado en la postulación del Reto;</li>
        <li>En todos los supuestos deberá EL USUARIO garantizar el respeto a los contenidos morales de los autores e inventores que hubieren participado con soluciones a un Reto en particular, ya fuere como postulador de retos a quien se le cedan los derechos sobre las soluciones o como proponente de soluciones que puede, de acuerdo con las anteriores reglas, conservar los derechos sobre tales soluciones o verse obligado a transferirlas formalmente a quien corresponda.</li>
    </ol>
    <p>La violación de cualquiera de los derechos y limitaciones indicados en la presente cláusula por parte del USUARIO habilitará a INTERACPEDIA, sin lugar a previa comunicación o aviso, a proceder con la cancelación de forma inmediata de la cuenta de usuario. </p>
    <p class="title1">iv. DERECHOS DE TERCEROS:</p>
    <p>INTERACPEDIA, a través de su plataforma web o la aplicación móvil, proporcionará información de servicios, retos o soluciones que serán postulados u ofrecidos por terceras personas o actores, las cuales se someterán a las condiciones puntuales que dichos terceros hubieren convenido y en los que el USUARIO participará directamente de acuerdo con sus preferencias. En dicho sentido, INTERACPEDIA le facilitará a sus usuarios una lista de posibles retos, proyectos y/o soluciones con el fin de que sea el USUARIO quien escoja aquél con el que se sientan más a gusto, entendiendo que INTERACPEDIA no facilita recomendaciones o promociones respecto de los retos, proyectos y/o soluciones de terceros, ni da garantías respecto de sus calidades.  En estos casos, INTERACPEDIA actuará como simple intermediario entre el USUARIO y los demás actores en la plataforma, y, si bien INTERACPEDIA facilita este canal, ello no implica que el USUARIO necesariamente deba participar en uno u otro proyecto, ni escoger una u otra solución, de acuerdo con las opciones propuestas por INTERACPEDIA, siendo libre de escoger cualquier otro proyecto o solución externos o postular sus propios retos y/o soluciones.</p>
    <p>Para dichos efectos, el USUARIO declara conocer y aceptar que la información compartida a través de INTERACPEDIA en estos casos se encuentra basada en la información compartida o proporcionada por los demás actores o usuarios y, en consecuencia, ellos son enteramente responsables por sus condiciones, la disponibilidad, premios e incentivos, u otra información que se comparta a través del sitio web o la aplicación móvil. Si bien INTERACPEDIA valida dicha información, no se hace responsable por aquellos errores, inexactitudes u otros que puedan presentarse en la información suministrada por terceros usuarios o actores, tanto en la postulación de retos como en la proposición de soluciones, siendo así que los usuarios o actores serán los únicos responsables respecto de la información que comparten a través del sitio web o la aplicación móvil INTERACPEDIA y sólo ellos se harán cargo de garantizarlos. </p>
    <p>El orden de las listas de retos, proyectos y/o soluciones de usuarios y actores que puedan postular o proponer aquellos en cada caso será facilitada por INTERACPEDIA en consideración al criterio que cada usuario desee, bien sea conforme a los precios ofrecidos o el orden alfabético de los proveedores, entre otros que resulten aplicables. No obstante, INTERACPEDIA se reserva el derecho a habilitar espacios promocionales para los diferentes actores quienes, de acuerdo con su ubicación, podrán aparecer en uno u otro lugar.</p>
    <p>El USUARIO, una vez hace uso de los servicios ofrecidos a través de la plataforma INTERACPEDIA, garantiza que al postular retos o proponer soluciones no está vulnerando derechos de terceros, tales como pero no limitados a derechos de autor, de imagen y de propiedad industrial. INTERACPEDIA no se hace responsable de los contenidos que sean publicados en su plataforma y con los cuales se vulneren derechos de terceros; no obstante, en caso de los usuarios no dar cumplimiento a lo estipulado en esta cláusula, INTERACPEDIA se reserva el derecho de eliminar de su plataforma estos contenidos y de eliminar y bloquear la cuenta de usuario del infractor.</p>
    <p class="title1">v. EXONERACIÓN DE RESPONSABILIDAD</p>
    <p>INTERACPEDIA no se hace responsable por la información, sin importar su contenido, que terceros compartan a través de su plataforma web o aplicación móvil. En particular, INTERACPEDIA no se hace responsable respecto de los siguientes casos:</p>
    <ol type="a">
        <li>Cuando el usuario suministre información falsa o de terceros.</li>
        <li>Cuando el usuario haga uso de la plataforma para compartir contenidos falsos o que vayan en contra de la moral y las buenas costumbres y/o en detrimento o afectación de terceros.</li>
        <li>Cuando la información compartida en uso de la plataforma INTERACPEDIA infrinja derechos de propiedad intelectual de terceros.</li>
    </ol>
    <p>En cualquier de estos casos, INTERACPEDIA se reserva el derecho de eliminar y bloquear la cuenta del usuario que incurra en estas infracciones, así como de suprimir y retirar de su plataforma estos contenidos. </p>
    <p class="title1">vi. REQUERIMIENTOS TÉCNICOS PARA LA EXPERIENCIA DEL USUARIO:</p>
    <p>A efectos de hacer uso de la aplicación o el sitio web, el USUARIO deber contar con los siguientes requerimientos técnicos:</p>
    <ol type="a">
        <li>Conectividad a la red pública de internet</li>
    </ol>
    <p class="title1">vii. POLÍTICA DE PRIVACIDAD Y PROTECCIÓN DE DATOS:</p>
    <p class="title2">a. Confidencialidad</p>
    <p>En virtud del presente documento, la información que INTERACPEDIA recopile de los usuarios en razón de los servicios suministrados a través de la plataforma, y que el usuario acepta proveer por medio de la aceptación de estos términos y condiciones, será utilizada de manera confidencial, no será divulgada de alguna manera por fuera de dichas circunstancias o eventos ni compartida con terceros, y será utilizada única y exclusivamente con el propósito para el cual dicha información es compartida y divulgada. Esta obligación de reserva y confidencialidad consiste en la abstención de usar, facilitar, divulgar o revelar, la información suministrada con ocasión de los servicios suministrados por INTERACPEDIA, sin obligación legal de hacerlo o sin consentimiento expreso por escrito del titular de la información.  No obstante, el USUARIO acepta y reconoce que su información permitirá generar análisis y estadísticas globales relacionada con los datos por el suministrados, más nunca individuales.</p>
    <p>INTERACPEDIA garantiza que protegerá por todos los medios la información confidencial, comprometiéndose a protegerla de la misma forma y en el mismo grado en que protege su propia información.</p>
    <p class="title2">b. Autorización para el tratamiento de datos personales y encargado del tratamiento</p>
    <p>En virtud de los dispuesto en la Ley 1581 de 2012 y demás decretos y normas complementarias el USUARIO, al aceptar estos términos y condiciones, autoriza de forma libre, expresa, voluntaria y por escrito a INTERACPEDIA para recolectar, recaudar, almacenar, usar, circular, suprimir, procesar, compilar, intercambiar, dar tratamiento, actualizar y disponer de los datos personales que han sido suministrados en virtud de los servicios proveídos por INTERACPEDIA y a los cuales se accede con la aceptación de estos términos y condiciones y que serán incorporados en distintas bases o bancos de datos de titularidad de INTERACPEDIA.</p>
    <p>Dicha información será utilizada exclusivamente en el desarrollo de las funciones y herramientas propias de la plataforma INTERACPEDIA. Para dichos efectos, el USUARIO declara conocer, al aceptar estos términos y condiciones, que la confidencialidad y protección de datos estipulados en esos términos de uso aplicarán a toda aquella información personal que el usuario ingresa de manera libre y voluntaria a la red de INTERACPEDIA a través de sus contenidos, así como aquellas que son de obligatorio ingreso, tales como nombre de usuario y contraseña.</p>
    <p>El usuario podrá, de forma expresa, directa, inequívoca y por escrito solicitarle a INTERACPEDIA que sus datos sean actualizados, rectificados o suprimidos de las bases o bancos de datos pertinentes. Para ello, el usuario podrá comunicarse con INTERACPEDIA a través del correo electrónico que se habilite para estas comunicaciones o cualquier otro medio habilitado para tal fin en la plataforma web o aplicación móvil, toda vez que éste es el responsable y encargado del tratamiento de los datos personales o información que se comparta a través de la plataforma.</p>
    <p>Del mismo modo, el USUARIO autoriza que sus datos sean compartidos con terceras personas cuando aquellos sean requeridos en uno u otro proyecto, reto o solución, entendiendo que al participar en dichos proyectos como postulador de retos y/o proponente de soluciones está consintiendo en que su información sea compartida otros usuarios o actores de la red INTERACPEDIA, salvo que expresamente hubiere señalado interés en permanecer en el anonimato. En aquellos casos en que el participante desee permanecer en anonimato, este reconoce y acepta que, como mínimo, deberá compartir su información con INTERACPEDIA u otros, según se especifique en cada reto. Si no tuviera interés en compartir su información en ningún supuesto, absténgase de hacer uso de los servicios de INTERACPEDIA.</p>
    <p class="title2">c. Información que se recopila</p>
    <p>Entre las clases de datos que se recopilan a mediante el uso de la plataforma de se encuentran: nombre de usuario, contraseña y dirección de correo electrónico, imágenes o fotografías que son compartidas en la plataforma, comentarios, likes y shares que se realizan de otros contenidos, así como videos, ideas, infographics, follow/seguir, artículos, twitts, presentaciones y otros con tales características. Otros datos pueden ser recogidos de manera automática en razón de las cookies o de tecnologías similares, tales como la ubicación del usuario y algunas preferencias. El USUARIO reconoce y acepta que todos estos datos serán utilizados para la promoción de retos, proyectos, perfiles y la misma plataforma web o aplicación móvil INTERACPEDIA.</p>
    <p>El usuario asume la responsabilidad por los datos personales suministrados o compartidos a través de la plataforma y declara que tiene derecho a comunicarlos o difundirlos públicamente, liberando a INTERACPEDIA de toda responsabilidad al respecto. Para ello, se cuenta con una política de verificación que consiste en confirmar, vía email, que es el titular de la información o que es un tercero autorizado para suministrarla.</p>
    <p class="title2">d. Modalidades de tratamiento de la información recopilada</p>
    <p>INTERACPEDIA como responsable del tratamiento de la información recolectada con el uso de la plataforma, le dará tratamiento a estos datos de manera adecuada y adoptará las medidas de seguridad apropiadas para impedir el acceso, revelación, alteración o destrucción no autorizada de aquellos. El tratamiento de datos se realiza siguiendo procedimientos y modalidades organizativas estrictamente relacionadas con la finalidad de permitir la prestación de los servicios propios de la plataforma, así como para las siguientes finalidades: gestión de direcciones de correo electrónico y envío de mensajes, recordar la información después de registrarse, y actualizar automáticamente el social feed o la plataforma de INTERACPEDIA donde los usuarios comparten sus contenidos.</p>
    <p>Además del social feed de la aplicación, el usuario puede divulgar de manera voluntaria otros contenidos en otras redes sociales tales como, pero no limitado a Instagram, Twitter, Youtube, Pinteres, Blogger y Facebook. INTERACPEDIA no se hace responsable de ningún daño o perjuicio generado en virtud de la publicación de contenidos en estas u otras plataformas diferentes a INTERACPEDIA ni del tratamiento que los titulares de dichas aplicaciones realicen de los datos del USUARIO.</p>
    <p class="title2">e. Solicitud de información, quejas y reclamos</p>
    <p>En aquellos casos en que el USUARIO requiera información, INTERACPEDIA verificará la legitimización del usuario para presentar dicha solicitud y, siempre y cuando ello sea constatado, contará con un término máximo de diez (10) días hábiles para contestarla, contados a partir de la fecha de recepción de la solicitud. Si hubiere alguna dificultad para contestar la consulta en dicho término, INTERACPEDIA le informará al usuario la razón por la cual tardará su respuesta, bajo el entendido de que no podrá superar los cinco (5) días hábiles siguientes al vencimiento del término inicial. </p>
    <p>Del mismo modo, podrá el USUARIO presentar quejas y reclamos de acuerdo con las siguientes especificaciones: i) el reclamo se formulará mediante solicitud dirigida INTERACPEDIA, con la identificación del titular de la información, la descripción de los hechos que dan lugar al reclamo, la dirección, y acompañando los documentos que se quiera hacer valer. Si el reclamo resulta incompleto, se requerirá al interesado dentro de los cinco (5) días siguientes a la recepción del reclamo para que subsane las fallas. Transcurridos dos (2) meses desde la fecha del requerimiento, sin que el solicitante presente la información requerida, se entenderá que ha desistido del reclamo. En caso de que quien reciba el reclamo no sea competente para resolverlo, INTERACPEDIA dará traslado a quien corresponda en un término máximo de dos (2) días hábiles e informará de la situación al interesado; ii) una vez recibido el reclamo completo, se incluirá en la base de datos una leyenda que diga "reclamo en trámite" y el motivo del mismo, en un término no mayor a dos (2) días hábiles; iii) INTERACPEDIA cuenta con un término de quince (15) días hábiles para atender el reclamo, contados a partir del día siguiente a la fecha de su recibo. Cuando no fuere posible atender el reclamo dentro de dicho término, INTERACPEDIA le informará al interesado los motivos de la demora y la fecha en que se atenderá su reclamo, la cual en ningún caso podrá superar los ocho (8) días hábiles siguientes al vencimiento del primer término. </p>
    <p class="title2">f. Titularidad y veracidad de la información</p>
    <p>El usuario es el único responsable de mantener su contraseña y la información de su cuenta. INTERACPEDIA parte del supuesto de que toda la información suministrada por los usuarios es verdadera, no haciéndose responsable por los daños o perjuicios que puedan surgir con ocasión de la falsedad de dicha información.</p>
    <p class="title1">viii. CLÁUSULA COMPROMISORIA:</p>
    <p>Toda controversia o diferencia relativa a este contrato, a su ejecución, a su liquidación, al cumplimiento de cualquiera de las obligaciones señaladas en el mismo y las que surgieran entre las partes, se resolverán por un Tribunal de Arbitramento que funcionará en el Centro de Conciliación y Arbitraje de la Cámara de Comercio de la ciudad de Medellín, que se sujetará a lo dispuesto en la Ley 1582 de 2012 y sus Decretos Reglamentarios y a las demás disposiciones legales que los reglamenten, adicionen o modifiquen y de acuerdo con las siguientes reglas: a. El Tribunal estará integrado por uno o tres árbitros según sea de menor o mayor cuantía, respectivamente. b. El Tribunal decidirá en Derecho. c. El Tribunal funcionará en el Centro de Conciliación y Arbitraje de la Cámara de Comercio de Medellín. </p>
    <p class="title1">ix. DOMICILIO Y LEGISLACIÓN APLICABLE:</p>
    <p>Para todos los efectos legales se estipula como lugar de cumplimiento de las obligaciones derivadas de estos términos y condiciones la ciudad de Medellín.</p>
    <p>En lo no previsto en este escrito, estos términos y condiciones se regirán por la ley colombiana aplicable y, en especial, por dispuesto en el Código Civil, el Código de Comercio y la Ley 527 de 1.999, todos ellos de Colombia.</p>
    <p class="title1">x. VIGENCIA Y MODIFICACIÓN DE TÉRMINOS Y CONDICIONES:</p>
    <p>Estos términos y condiciones, así como la política de privacidad y protección de datos personales acá contenida, es efectiva a partir de la fecha de su publicación, el día xx de xxx de 2015. No obstante, INTERACPEDIA se reserva el derecho a efectuar, en cualquier momento y sin previo aviso, actualizaciones o modificaciones a estos términos y condiciones en atención a los requerimientos que puedan presentarse, de orden interno o externo, para la correcta prestación de sus servicios.  </p>
    <p>Toda modificación o actualización supondrá la facultad de agregar o eliminar información y será publicada o puesta a disposición de los usuarios a través de cualquiera de los siguientes canales: el sitio web, la aplicación móvil, el correo electrónico (entendiendo por tal el último proporcionado), o anuncios visibles en cualquier de los anteriores o centros de atención. Con ello, podrá el usuario decidir si continuar o no utilizando los servicios ofrecidos por INTERACPEDIA. </p>
    <p>Este sitio Web incluye avisos sobre servicios y productos propios y de terceras personas, cuyos términos deben observarse y seguirse. Ningún contenido de esta plataforma puede ser copiado, reproducido, recopilado, cargado, publicado, transmitido, distribuido, o utilizado sin el previo y expreso consentimiento de INTERACPEDIA o su titular.</p>
@stop